### ISSUE TITLE
No module named `darkdetect`

### ISSUE THREAD

**Issue by vsheg** [EBjerrum/rdeditor#22]
Hi, I installed `rdeditor 0.3.0` using `pipx` for `Python 3.12.4` on macOS 14.5 (ARM). 

```bash
$ pipx install rdeditor
```

I guess, `darkdetect` must be added to dependencies explicitly, as:
```
$ rdEditor
Traceback (most recent call last):
  File "/Users/sheg/.local/bin/rdEditor", line 5, in <module>
    from rdeditor.rdEditor import launch
  File "/Users/sheg/.local/pipx/venvs/rdeditor/lib/python3.12/site-packages/rdeditor/__init__.py", line 9, in <module>
    from .rdEditor import MainWindow
  File "/Users/sheg/.local/pipx/venvs/rdeditor/lib/python3.12/site-packages/rdeditor/rdEditor.py", line 16, in <module>
    import darkdetect
ModuleNotFoundError: No module named 'darkdetect'
```

After I installed `darkdetect` manually, I was able to run `rdEditor` 

```bash
$ pipx inject rdeditor darkdetect
  injected package darkdetect into venv rdeditor
done! ✨ 🌟 ✨
$ rdEditor
```

**Comment by EBjerrum** [comment]
Thanks, i'll update the install file

**Comment by EBjerrum** [comment]
Turned out the import was unneeded. The newest version on PyPI  (0.3.0.1) should work even without darkdetect installed.
